from xml.etree import ElementTree as ET
from xml.dom import minidom
from ...models.diagram import Diagram, ElementType
from ...models.label import Label
from ...models.export import ExportConfig

def generate_svg(diagram: Diagram, labels: list[Label], config: ExportConfig) -> str:
    """
    Generate an SVG string representing the diagram and its braille labels.
    """
    
    # 1. Determine Scale Factor
    # We map diagram.canvas (in pixels) to config dimensions (in physical units)
    canvas_w = diagram.canvas.width if diagram.canvas else 800
    canvas_h = diagram.canvas.height if diagram.canvas else 600
    
    # Scale based on width (maintain aspect ratio)
    scale = config.width / canvas_w
    
    # Calculate actual output height based on scale
    out_h = canvas_h * scale
    
    # 2. Setup root SVG
    svg = ET.Element('svg', {
        'xmlns': 'http://www.w3.org/2000/svg',
        'width': f'{config.width}{config.unit.value}',
        'height': f'{out_h}{config.unit.value}',
        'viewBox': f'0 0 {config.width} {out_h}',
        'id': f'diagram-{diagram.id}'
    })
    
    # Optional metadata
    if config.include_metadata:
        title = ET.SubElement(svg, 'title')
        title.text = f"Tactile Diagram {diagram.id}"
        desc = ET.SubElement(svg, 'desc')
        desc.text = "Generated by TactileEd"
        
    # CSS Styles
    style = ET.SubElement(svg, 'style')
    style.text = f"""
        .tactile-line {{ stroke: black; stroke-width: {config.stroke_width_mm}; fill: none; }}
        .tactile-fill {{ stroke: black; stroke-width: {config.stroke_width_mm}; fill: black; }}
        .tactile-text {{ font-family: 'Braille', 'Arial Unicode MS', 'Segoe UI Symbol', 'Noto Sans Braille', 'DejaVu Sans', monospace; font-size: {5.5 * scale}px; fill: black; }}
        .leader-line {{ stroke: black; stroke-width: {config.stroke_width_mm / 2}; stroke-dasharray: 2,2; fill: none; }}
    """
    
    # 3. Add Geometry
    geom_group = ET.SubElement(svg, 'g', {'id': 'geometry'})
    for el in diagram.elements:
        g = el.geometry
        el_id = f"el-{el.id}"
        
        if el.type == ElementType.LINE and "x1" in g:
            ET.SubElement(geom_group, 'line', {
                'id': el_id,
                'x1': str(g["x1"] * scale),
                'y1': str(g["y1"] * scale),
                'x2': str(g["x2"] * scale),
                'y2': str(g["y2"] * scale),
                'class': 'tactile-line'
            })
            
        elif el.type == ElementType.CIRCLE and "cx" in g:
            ET.SubElement(geom_group, 'circle', {
                'id': el_id,
                'cx': str(g["cx"] * scale),
                'cy': str(g["cy"] * scale),
                'r': str(g["r"] * scale),
                'class': 'tactile-line'
            })
            
        elif el.type in (ElementType.POLYGON, ElementType.FILLED_REGION) and "points" in g:
            points_str = " ".join([f"{p['x']*scale},{p['y']*scale}" for p in g["points"]])
            cls_name = 'tactile-fill' if el.type == ElementType.FILLED_REGION else 'tactile-line'
            ET.SubElement(geom_group, 'polygon', {
                'id': el_id,
                'points': points_str,
                'class': cls_name
            })
            
        elif el.type == ElementType.CURVE and "points" in g:
            # Approximate curve as polyline for robust SVG without complex bezier fitting
            points_str = " ".join([f"{p['x']*scale},{p['y']*scale}" for p in g["points"]])
            ET.SubElement(geom_group, 'polyline', {
                'id': el_id,
                'points': points_str,
                'class': 'tactile-line'
            })
            
    # 4. Add Labels
    label_group = ET.SubElement(svg, 'g', {'id': 'labels'})
    for lbl in labels:
        if not lbl.placement:
            continue
            
        lbl_id = f"lbl-{lbl.id}"
        
        # Leader line
        if lbl.placement.leader_line:
            ll = lbl.placement.leader_line
            ET.SubElement(label_group, 'line', {
                'x1': str(ll.start.x * scale),
                'y1': str(ll.start.y * scale),
                'x2': str(ll.end.x * scale),
                'y2': str(ll.end.y * scale),
                'class': 'leader-line'
            })
            
        # Text element (Note: SVG text y is the baseline, so we offset by height)
        # Using the Unicode Braille characters
        text_str = lbl.braille.braille_unicode if lbl.braille.braille_unicode else lbl.text
        
        x_pos = lbl.placement.position.x * scale
        y_pos = (lbl.placement.position.y + lbl.placement.height) * scale
        
        text_el = ET.SubElement(label_group, 'text', {
            'id': lbl_id,
            'x': str(x_pos),
            'y': str(y_pos),
            'class': 'tactile-text'
        })
        text_el.text = text_str
        
    # Output formatted XML
    xml_str = ET.tostring(svg, encoding='utf-8').decode('utf-8')
    parsed = minidom.parseString(xml_str)
    return parsed.toprettyxml(indent="  ")
